[2024-12-15T22:52:59.246+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_library_imports.test_imports manual__2024-12-15T22:52:56.468079+00:00 [queued]>
[2024-12-15T22:52:59.257+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_library_imports.test_imports manual__2024-12-15T22:52:56.468079+00:00 [queued]>
[2024-12-15T22:52:59.258+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-12-15T22:52:59.272+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): test_imports> on 2024-12-15 22:52:56.468079+00:00
[2024-12-15T22:52:59.278+0000] {standard_task_runner.py:60} INFO - Started process 2860 to run task
[2024-12-15T22:52:59.281+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_library_imports', 'test_imports', 'manual__2024-12-15T22:52:56.468079+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp5q0758os']
[2024-12-15T22:52:59.283+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask test_imports
[2024-12-15T22:52:59.340+0000] {task_command.py:423} INFO - Running <TaskInstance: test_library_imports.test_imports manual__2024-12-15T22:52:56.468079+00:00 [running]> on host 5324727f1801
[2024-12-15T22:52:59.449+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_library_imports' AIRFLOW_CTX_TASK_ID='test_imports' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T22:52:56.468079+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T22:52:56.468079+00:00'
[2024-12-15T22:52:59.452+0000] {dag1.py:11} INFO - Pandas version: 2.0.3
[2024-12-15T22:52:59.465+0000] {base.py:83} INFO - Using connection ID 'mysql_connection' for task execution.
[2024-12-15T22:53:41.649+0000] {dag1.py:25} ERROR - Error during imports or MySQL connection: (2002, "Can't connect to server on 'database-1.c1eo8uma67by.us-east-2.rds.amazonaws.com' (111)")
[2024-12-15T22:53:41.650+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-12-15T22:53:41.662+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=test_library_imports, task_id=test_imports, execution_date=20241215T225256, start_date=20241215T225259, end_date=20241215T225341
[2024-12-15T22:53:41.702+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-15T22:53:41.719+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
