[2024-12-18T02:30:06.728+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_library_imports.test_imports manual__2024-12-18T02:30:03.870759+00:00 [queued]>
[2024-12-18T02:30:06.738+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_library_imports.test_imports manual__2024-12-18T02:30:03.870759+00:00 [queued]>
[2024-12-18T02:30:06.739+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-12-18T02:30:06.756+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): test_imports> on 2024-12-18 02:30:03.870759+00:00
[2024-12-18T02:30:06.764+0000] {standard_task_runner.py:60} INFO - Started process 952 to run task
[2024-12-18T02:30:06.768+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_library_imports', 'test_imports', 'manual__2024-12-18T02:30:03.870759+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpdz7syq0z']
[2024-12-18T02:30:06.769+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask test_imports
[2024-12-18T02:30:06.826+0000] {task_command.py:423} INFO - Running <TaskInstance: test_library_imports.test_imports manual__2024-12-18T02:30:03.870759+00:00 [running]> on host d9ce99263c32
[2024-12-18T02:30:06.928+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_library_imports' AIRFLOW_CTX_TASK_ID='test_imports' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T02:30:03.870759+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-18T02:30:03.870759+00:00'
[2024-12-18T02:30:06.931+0000] {oauth2.py:461} INFO - User authentication requires interaction with your web browser. Once you enter your credentials and give authorization, you will be redirected to a url.  Paste that url you were directed to to complete the authorization.
[2024-12-18T02:30:06.932+0000] {oauth2.py:426} INFO - Opened https://accounts.spotify.com/authorize?client_id=829475f2db444c5cbd5c1026b0ee8ad2&response_type=code&redirect_uri=http%3A%2Flocalhost%3A8080%2Foauth2callback&scope=user-read-recently-played in your browser
[2024-12-18T02:30:06.933+0000] {logging_mixin.py:188} INFO - Enter the URL you were redirected to: 
[2024-12-18T02:30:06.934+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 108, in _get_user_input
    return raw_input(prompt)
NameError: name 'raw_input' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag1.py", line 14, in fetch_and_insert_spotify
    recently_played_tracks = spotify_hook.getRecentlyPlayed()
  File "/opt/airflow/dags/common/hooks/SpotifyHook.py", line 43, in getRecentlyPlayed
    results = sp.current_user_recently_played(limit=50)  # Adjust the limit as needed
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 1514, in current_user_recently_played
    return self._get(
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 327, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 251, in _internal_call
    headers = self._auth_headers()
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 242, in _auth_headers
    token = self.auth_manager.get_access_token(as_dict=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 525, in get_access_token
    "code": code or self.get_auth_response(),
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 489, in get_auth_response
    return self._get_auth_response_interactive(open_browser=open_browser)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 440, in _get_auth_response_interactive
    response = self._get_user_input(prompt)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 110, in _get_user_input
    return input(prompt)
EOFError: EOF when reading a line
[2024-12-18T02:30:06.965+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_library_imports, task_id=test_imports, execution_date=20241218T023003, start_date=20241218T023006, end_date=20241218T023006
[2024-12-18T02:30:06.986+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task test_imports (EOF when reading a line; 952)
[2024-12-18T02:30:07.021+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-18T02:30:07.044+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
