[2024-12-18T03:04:50.938+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_library_imports.test_imports manual__2024-12-18T02:30:03.870759+00:00 [queued]>
[2024-12-18T03:04:50.949+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_library_imports.test_imports manual__2024-12-18T02:30:03.870759+00:00 [queued]>
[2024-12-18T03:04:50.950+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-12-18T03:04:50.969+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): test_imports> on 2024-12-18 02:30:03.870759+00:00
[2024-12-18T03:04:50.977+0000] {standard_task_runner.py:60} INFO - Started process 1459 to run task
[2024-12-18T03:04:50.981+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_library_imports', 'test_imports', 'manual__2024-12-18T02:30:03.870759+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpz4_jumqi']
[2024-12-18T03:04:50.983+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask test_imports
[2024-12-18T03:04:51.058+0000] {task_command.py:423} INFO - Running <TaskInstance: test_library_imports.test_imports manual__2024-12-18T02:30:03.870759+00:00 [running]> on host d9ce99263c32
[2024-12-18T03:04:51.207+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_library_imports' AIRFLOW_CTX_TASK_ID='test_imports' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T02:30:03.870759+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-18T02:30:03.870759+00:00'
[2024-12-18T03:04:51.212+0000] {oauth2.py:461} INFO - User authentication requires interaction with your web browser. Once you enter your credentials and give authorization, you will be redirected to a url.  Paste that url you were directed to to complete the authorization.
[2024-12-18T03:04:51.213+0000] {oauth2.py:426} INFO - Opened https://accounts.spotify.com/authorize?client_id=829475f2db444c5cbd5c1026b0ee8ad2&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Foauth2callback&scope=user-read-recently-played in your browser
[2024-12-18T13:05:57.615+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: test_library_imports.test_imports manual__2024-12-18T02:30:03.870759+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-12-18T13:05:57.616+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: test_library_imports.test_imports manual__2024-12-18T02:30:03.870759+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-12-18T13:05:57.619+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-12-18T22:17:17.937+0000] {local_task_job_runner.py:211} ERROR - Heartbeat time limit exceeded!
[2024-12-18T22:17:18.561+0000] {process_utils.py:131} INFO - Sending 15 to group 1459. PIDs of all processes in the group: [1459]
[2024-12-18T22:17:18.624+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1459
[2024-12-18T22:17:19.326+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-18T22:17:21.824+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag1.py", line 14, in fetch_and_insert_spotify
    recently_played_tracks = spotify_hook.getRecentlyPlayed()
  File "/opt/airflow/dags/common/hooks/SpotifyHook.py", line 43, in getRecentlyPlayed
    results = sp.current_user_recently_played(limit=50)  # Adjust the limit as needed
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 1514, in current_user_recently_played
    return self._get(
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 327, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 251, in _internal_call
    headers = self._auth_headers()
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 242, in _auth_headers
    token = self.auth_manager.get_access_token(as_dict=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 525, in get_access_token
    "code": code or self.get_auth_response(),
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 480, in get_auth_response
    return self._get_auth_response_local_server(redirect_port)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 449, in _get_auth_response_local_server
    server.handle_request()
  File "/usr/local/lib/python3.8/socketserver.py", line 294, in handle_request
    ready = selector.select(timeout)
  File "/usr/local/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-18T22:17:24.498+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_library_imports, task_id=test_imports, execution_date=20241218T023003, start_date=20241218T030450, end_date=20241218T221724
[2024-12-18T22:17:25.936+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task test_imports (Task received SIGTERM signal; 1459)
[2024-12-18T22:17:27.665+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1459, status='terminated', exitcode=1, started='03:04:50') (1459) terminated with exit code 1
