[2025-01-12T00:53:59.393+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_etl.spotify_etl scheduled__2025-01-11T00:00:00+00:00 [queued]>
[2025-01-12T00:53:59.420+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_etl.spotify_etl scheduled__2025-01-11T00:00:00+00:00 [queued]>
[2025-01-12T00:53:59.425+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-01-12T00:53:59.519+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): spotify_etl> on 2025-01-11 00:00:00+00:00
[2025-01-12T00:53:59.541+0000] {standard_task_runner.py:60} INFO - Started process 226 to run task
[2025-01-12T00:53:59.548+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_etl', 'spotify_etl', 'scheduled__2025-01-11T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/spotify_etl_dag.py', '--cfg-path', '/tmp/tmpqavziwq5']
[2025-01-12T00:53:59.571+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask spotify_etl
[2025-01-12T00:53:59.706+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_etl.spotify_etl scheduled__2025-01-11T00:00:00+00:00 [running]> on host d9ce99263c32
[2025-01-12T00:53:59.851+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_etl' AIRFLOW_CTX_TASK_ID='spotify_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-11T00:00:00+00:00'
[2025-01-12T00:53:59.856+0000] {logging_mixin.py:188} INFO - Access token expired, refreshing...
[2025-01-12T00:54:00.436+0000] {extract.py:10} INFO - Retrieved 6 tracks from Spotify
[2025-01-12T00:54:00.437+0000] {transform.py:35} ERROR - Error transforming data: 'Track' object has no attribute 'id'
[2025-01-12T00:54:00.442+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_etl_dag.py", line 16, in etl_process
    transformed_songs, transformed_albums = transform_tracks(raw_data)
  File "/opt/airflow/dags/etl/transform.py", line 13, in transform_tracks
    'id': track.id,
AttributeError: 'Track' object has no attribute 'id'
[2025-01-12T00:54:00.488+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_etl, task_id=spotify_etl, execution_date=20250111T000000, start_date=20250112T005359, end_date=20250112T005400
[2025-01-12T00:54:00.523+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task spotify_etl ('Track' object has no attribute 'id'; 226)
[2025-01-12T00:54:00.585+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-01-12T00:54:00.621+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
